 # This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ml_api

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install poetry
      run: python -m pip install --upgrade pip && python -m pip install poetry==1.6.1
    - name: Install dependency
      run: poetry install --without lint
    - name: test
      run: poetry run pytest test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install poetry
        run: python -m pip install --upgrade pip && python -m pip install poetry==1.6.1
      - name: Install dependency
        run: poetry install
      - name: linter
        run: poetry run ruff .
      - name: type hints
        run: poetry run mypy .

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: pull project
        uses: actions/checkout@v3
      - name: Build and no push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ml_api:latest